### ISSUE TITLE
A failing command does not fail the action itself

### ISSUE THREAD

**Issue by ennru** [lightbend/kalix-action#2]

**Comment by visma-alexander-maslov** [comment]
any progress on this?

returning "proper" exit code from `kalix` binary might help. At the moment it is always `0` no matter was there an error or not

**Comment by olofwalker** [comment]
@visma-alexander-maslov Version 2.0.33 of the CLi is making its way out on the download site and brew now, it should set the exit code properly.

**Comment by ennru** [comment]
To fix this misbehaviour, we've now released v7.1
- https://github.com/lightbend/kalix-action/releases/tag/v7.1
